name: run-tests
on: [ push ]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn
    - name: Build all artifacts
      run: npm run build
    - name: Run unit tests
      run: npm test
